### ISSUE TITLE
Video validation is not working correctly

### ISSUE THREAD

**Issue by mzur** [biigle/videos#61]
An MPG video could be created but did not pass some validation during processing:
```
[2020-03-04 01:16:10] production.WARNING: Could not process new video 1448: Error while caching file 'https://xxxx.mpg': MIME type 'image/x-tga' not allowed.  
```

Also video 1449 is a MOV which cannot be read by the object tracking script:
```
[2020-03-04 01:47:28] production.ERROR: Error while executing Python script with '/var/www/vendor/biigle/videos/src/config/../resources/scripts/ObjectTracker.py /tmp/object_tracking_input_74321.json /tmp/object_tracking_output_74321.json':
Traceback (most recent call last):
  File "/var/www/vendor/biigle/videos/src/config/../resources/scripts/ObjectTracker.py", line 82, in <module>
    for keyframe in ObjectTracker(params):
  File "/var/www/vendor/biigle/videos/src/config/../resources/scripts/ObjectTracker.py", line 20, in __init__
    raise IOError('The video file could not be read: {}'.format(params['video_path']))
IOError: The video file could not be read: /var/www/storage/framework/cache/files/8af81c15d12ca942d2070d1cae4e725fd4bc7198b00b780b876a030f6a932acb {"exception":"[object] (Exception(code: 0): Error while executing Python script with '/var/www/vendor/biigle/videos/src/config/../resources/scripts/ObjectTracker.py /tmp/object_tracking_input_74321.json /tmp/object_tracking_output_74321.json':
Traceback (most recent call last):
  File \"/var/www/vendor/biigle/videos/src/config/../resources/scripts/ObjectTracker.py\", line 82, in <module>
    for keyframe in ObjectTracker(params):
  File \"/var/www/vendor/biigle/videos/src/config/../resources/scripts/ObjectTracker.py\", line 20, in __init__
    raise IOError('The video file could not be read: {}'.format(params['video_path']))
IOError: The video file could not be read: /var/www/storage/framework/cache/files/8af81c15d12ca942d2070d1cae4e725fd4bc7198b00b780b876a030f6a932acb at /var/www/vendor/biigle/videos/src/Jobs/TrackObject.php:188)
[stacktrace]
#0 /var/www/vendor/biigle/videos/src/Jobs/TrackObject.php(97): Biigle\\Modules\\Videos\\Jobs\\TrackObject->python('/var/www/vendor...')
#1 [internal function]: Biigle\\Modules\\Videos\\Jobs\\TrackObject->Biigle\\Modules\\Videos\\Jobs\\{closure}(Object(Biigle\\Modules\\Videos\\Video), '/var/www/storag...')
#2 /var/www/vendor/biigle/laravel-file-cache/src/FileCache.php(79): call_user_func(Object(Closure), Object(Biigle\\Modules\\Videos\\Video), '/var/www/storag...')
#3 [internal function]: Biigle\\FileCache\\FileCache->Biigle\\FileCache\\{closure}(Array, Array)
#4 /var/www/vendor/biigle/laravel-file-cache/src/FileCache.php(139): call_user_func(Object(Closure), Array, Array)
#5 /var/www/vendor/biigle/laravel-file-cache/src/FileCache.php(80): Biigle\\FileCache\\FileCache->batch(Array, Object(Closure))
#6 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(245): Biigle\\FileCache\\FileCache->get(Object(Biigle\\Modules\\Videos\\Video), Object(Closure))
#7 /var/www/vendor/biigle/videos/src/Jobs/TrackObject.php(110): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#8 /var/www/vendor/biigle/videos/src/Jobs/TrackObject.php(47): Biigle\\Modules\\Videos\\Jobs\\TrackObject->getTrackingKeyframes(Object(Biigle\\Modules\\Videos\\VideoAnnotation))
#9 [internal function]: Biigle\\Modules\\Videos\\Jobs\\TrackObject->handle()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(34): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#13 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Biigle\\Modules\\Videos\\Jobs\\TrackObject))
#17 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Biigle\\Modules\\Videos\\Jobs\\TrackObject))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Biigle\\Modules\\Videos\\Jobs\\TrackObject), false)
#20 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Biigle\\Modules\\Videos\\Jobs\\TrackObject))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Biigle\\Modules\\Videos\\Jobs\\TrackObject))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Biigle\\Modules\\Videos\\Jobs\\TrackObject))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#25 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(348): Illuminate\\Queue\\Jobs\\Job->fire()
#26 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(294): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(129): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'high,default', Object(Illuminate\\Queue\\WorkerOptions))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'high,default')
#30 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#31 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#32 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(34): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#33 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#36 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#37 /var/www/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#39 /var/www/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 /var/www/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /var/www/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 {main}
"} 
```

Fix the validation of the create video endpoint so only valid video formats are allowed!

**Comment by mzur** [comment]
I couldn't reproduce the error for video 1449. It's probably the same issue than mentioned in https://github.com/biigle/videos/issues/57#issuecomment-611501820.

A video codec validation should resolve both this issue and #57. The codec can be obtained as follows:

```php
$ffprobe = FFMpeg\FFProbe::create();
$ffprobe->streams($url)->videos()->first()->get('codec_name');
```

This seems to work with remote URLs without fetching the whole video file. Local video files must be checked using the file cache. Valid codecs are: `h264`, `vp8`, `vp9` and `av1`.
